name="Template";
tooltip="Template";
overview="DayZ Mod Template";
picture="Template/data/picture.paa";
logoSmall="Template/data/logoSmall.paa";
logo="Template/data/logo.paa";
logoOver="Template/data/logo.paa";
action="https://steamcommunity.com/sharedfiles/filedetails/?id=0000000000";
author="SteamName";
version="1.0";
